import { Schema } from "./schema";

type Dict = { [key: string]: keyof Schema };

export const transliterateMap: Dict = {
  Α: "CAPITAL_ALPHA", // GREEK CAPITAL LETTER ALPHA (U+0391)
  Β: "CAPITAL_BETA", // GREEK CAPITAL LETTER BETA (U+0392)
  Γ: "CAPITAL_GAMMA", // GREEK CAPITAL LETTER GAMMA (U+0393)
  Δ: "CAPITAL_DELTA", // GREEK CAPITAL LETTER DELTA (U+0394)
  Ε: "CAPITAL_EPSILON", // GREEK CAPITAL LETTER EPSILON (U+0395)
  Ζ: "CAPITAL_ZETA", // GREEK CAPITAL LETTER ZETA (U+0396)
  Η: "CAPITAL_ETA", // GREEK CAPITAL LETTER ETA (U+0397)
  Θ: "CAPITAL_THETA", // GREEK CAPITAL LETTER THETA (U+0398)
  Ι: "CAPITAL_IOTA", // GREEK CAPITAL LETTER IOTA (U+0399)
  Κ: "CAPITAL_KAPPA", // GREEK CAPITAL LETTER KAPPA (U+039A)
  Λ: "CAPITAL_LAMDA", // GREEK CAPITAL LETTER LAMDA (U+039B)
  Μ: "CAPITAL_MU", // GREEK CAPITAL LETTER MU (U+039C)
  Ν: "CAPITAL_NU", // GREEK CAPITAL LETTER NU (U+039D)
  Ξ: "CAPITAL_XI", // GREEK CAPITAL LETTER XI (U+039E)
  Ο: "CAPITAL_OMICRON", // GREEK CAPITAL LETTER OMICRON (U+039F)
  Π: "CAPITAL_PI", // GREEK CAPITAL LETTER PI (U+03A0)
  Ρ: "CAPITAL_RHO", // GREEK CAPITAL LETTER RHO (U+03A1)
  Σ: "CAPITAL_SIGMA", // GREEK CAPITAL LETTER SIGMA (U+03A3)
  Τ: "CAPITAL_TAU", // GREEK CAPITAL LETTER TAU (U+03A4)
  Υ: "CAPITAL_UPSILON", // GREEK CAPITAL LETTER UPSILON (U+03A5)
  Φ: "CAPITAL_PHI", // GREEK CAPITAL LETTER PHI (U+03A6)
  Χ: "CAPITAL_CHI", // GREEK CAPITAL LETTER CHI (U+03A7)
  Ψ: "CAPITAL_PSI", // GREEK CAPITAL LETTER PSI (U+03A8)
  Ω: "CAPITAL_OMEGA", // GREEK CAPITAL LETTER OMEGA (U+03A9)
  α: "SMALL_ALPHA", // GREEK SMALL LETTER ALPHA (U+03B1)
  β: "SMALL_BETA", // GREEK SMALL LETTER BETA (U+03B2)
  γ: "SMALL_GAMMA", // GREEK SMALL LETTER GAMMA (U+03B3)
  δ: "SMALL_DELTA", // GREEK SMALL LETTER DELTA (U+03B4)
  ε: "SMALL_EPSILON", // GREEK SMALL LETTER EPSILON (U+03B5)
  ζ: "SMALL_ZETA", // GREEK SMALL LETTER ZETA (U+03B6)
  η: "SMALL_ETA", // GREEK SMALL LETTER ETA (U+03B7)
  θ: "SMALL_THETA", // GREEK SMALL LETTER THETA (U+03B8)
  ι: "SMALL_IOTA", // GREEK SMALL LETTER IOTA (U+03B9)
  κ: "SMALL_KAPPA", // GREEK SMALL LETTER KAPPA (U+03BA)
  λ: "SMALL_LAMDA", // GREEK SMALL LETTER LAMDA (U+03BB)
  μ: "SMALL_MU", // GREEK SMALL LETTER MU (U+03BC)
  ν: "SMALL_NU", // GREEK SMALL LETTER NU (U+03BD)
  ξ: "SMALL_XI", // GREEK SMALL LETTER XI (U+03BE)
  ο: "SMALL_OMICRON", // GREEK SMALL LETTER OMICRON (U+03BF)
  π: "SMALL_PI", // GREEK SMALL LETTER PI (U+03C0)
  ρ: "SMALL_RHO", // GREEK SMALL LETTER RHO (U+03C1)
  ς: "SMALL_FINAL_SIGMA", // GREEK SMALL LETTER FINAL SIGMA (U+03C2)
  σ: "SMALL_SIGMA", // GREEK SMALL LETTER SIGMA (U+03C3)
  τ: "SMALL_TAU", // GREEK SMALL LETTER TAU (U+03C4)
  υ: "SMALL_UPSILON", // GREEK SMALL LETTER UPSILON (U+03C5)
  φ: "SMALL_PHI", // GREEK SMALL LETTER PHI (U+03C6)
  χ: "SMALL_CHI", // GREEK SMALL LETTER CHI (U+03C7)
  ψ: "SMALL_PSI", // GREEK SMALL LETTER PSI (U+03C8)
  ω: "SMALL_OMEGA" // GREEK SMALL LETTER OMEGA (U+03C9)
};

// Characters from NFKD normalization
// "\u{00B7}": "", // GREEK ANO TELEIA (U+0387) > MIDDLE DOT
// "\u{0300}": "", // VARIA > COMBINING GRAVE ACCENT
// "\u{0301}": "", // TONOS/OXIA > COMBINING ACUTE ACCENT
// "\u{0304}": "", // MACRON > COMBINING MACRON
// "\u{0306}": "", // VRACHY > COMBINING BREVE
// "\u{0313}": "", // PSILI > COMBINING COMMA ABOVE
// //   "\u{0314}": "\u{0314}", // DASIA (i.e. rough breathing mark) > COMBINING REVERSED COMMA ABOVE
// "\u{0342}": "", // PERISPOMENI > COMBINING GREEK PERISPOMENI
// "\u{0345}": "" // YPOGEGRAMMENI > COMBINING GREEK YPOGEGRAMMENI
